name = "tdi_project"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TdiProject", "main"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_lib]]
name = "TdiProject"

[[lean_exe]]
name = "main"
root = "Main"